/**
 * Company: CETAM
 * Project: QParking
 * File: app_icons.dart
 * Created on: 30/11/2025
 * Created by: Carlos Adair Bautista Godinez
 * Approved by: Daniel Yair Mendoza Alvarez
 */

import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:flutter/material.dart';
import 'package:qparking/core/widgets/app_icon.dart';

enum AppIconName{
  //Users & Roles
  user,
  userCircle,
  userAdd,
  userRemove,
  userGroup,
  userTie,
  //Actions
  add,
  edit,
  delete,
  view,
  save,
  cancel,
  send,
  download,
  upload,
  search,
  refreshArrows,
  //Alerts & Notifications
  success,
  error,
  warning,
  info,
  pending,
  notification,
  notificationOff,
  //Files & Directories
  file,
  filePdf,
  fileWord,
  fileExcel,
  fileImage,
  folder,
  folderOpen,
  uploadArrow,
  downloadArrow,
  attachment,
  //Process, Settings & Loading
  refreshArrow,
  loading,
  settings,
  process,
  sync,
  //Nav & UI
  home,
  dashboard,
  menu,
  back,
  forward,
  up,
  down,
  close,
  externalLink,
  //Payment
  money,
  coins,
  card,
  invoice,
  chartUp,
  chartDown,
  //Comms
  email,
  phone,
  chat,
  support,
  help,
  //Lists & Filters
  list,
  listOrdered,
  filter,
  sort,
  sortUp,
  sortDown,
  checkList,
  //Access & Security
  login,
  logout,
  lock,
  unlock,
  key,
  shield,
  //Reports
  report,
  reportBar,
  reportPie,
  print,
  downloadReport,
  //QrCode
  qrCode,
  //Parking
  parking,
  //Subscription
  medal,
}

final Map<AppIconName, IconData> kAppIconMap = {
  AppIconName.user: FontAwesomeIcons.solidUser,
  AppIconName.userCircle: FontAwesomeIcons.solidCircleUser,
  AppIconName.userAdd: FontAwesomeIcons.userPlus,
  AppIconName.userRemove: FontAwesomeIcons.userMinus,
  AppIconName.userGroup: FontAwesomeIcons.users,
  AppIconName.userTie: FontAwesomeIcons.userTie,
  AppIconName.add: FontAwesomeIcons.plus,
  AppIconName.edit: FontAwesomeIcons.solidPenToSquare,
  AppIconName.delete: FontAwesomeIcons.trash,
  AppIconName.view: FontAwesomeIcons.solidEye,
  AppIconName.save: FontAwesomeIcons.solidFloppyDisk,
  AppIconName.cancel: FontAwesomeIcons.xmark,
  AppIconName.send: FontAwesomeIcons.solidPaperPlane,
  AppIconName.download: FontAwesomeIcons.download,
  AppIconName.upload: FontAwesomeIcons.upload,
  AppIconName.search: FontAwesomeIcons.magnifyingGlass,
  AppIconName.refreshArrows: FontAwesomeIcons.arrowsRotate,
  AppIconName.success: FontAwesomeIcons.solidCircleCheck,
  AppIconName.error: FontAwesomeIcons.circleXmark,
  AppIconName.warning: FontAwesomeIcons.triangleExclamation,
  AppIconName.info: FontAwesomeIcons.circleInfo,
  AppIconName.pending: FontAwesomeIcons.solidClock,
  AppIconName.notification: FontAwesomeIcons.solidBell,
  AppIconName.notificationOff: FontAwesomeIcons.solidBellSlash,
  AppIconName.file: FontAwesomeIcons.solidFile,
  AppIconName.filePdf: FontAwesomeIcons.solidFilePdf,
  AppIconName.fileWord: FontAwesomeIcons.solidFileWord,
  AppIconName.fileExcel: FontAwesomeIcons.solidFileExcel,
  AppIconName.fileImage: FontAwesomeIcons.solidFileImage,
  AppIconName.folder: FontAwesomeIcons.solidFolder,
  AppIconName.folderOpen: FontAwesomeIcons.solidFolderOpen,
  AppIconName.uploadArrow: FontAwesomeIcons.arrowUp,
  AppIconName.downloadArrow: FontAwesomeIcons.arrowDown,
  AppIconName.attachment: FontAwesomeIcons.paperclip,
  AppIconName.refreshArrow: FontAwesomeIcons.arrowRotateRight,
  AppIconName.loading: FontAwesomeIcons.spinner,
  AppIconName.settings: FontAwesomeIcons.gear,
  AppIconName.process: FontAwesomeIcons.gears,
  AppIconName.sync: FontAwesomeIcons.sync,
  AppIconName.home: FontAwesomeIcons.house,
  AppIconName.dashboard: FontAwesomeIcons.gaugeHigh,
  AppIconName.menu: FontAwesomeIcons.bars,
  AppIconName.back: FontAwesomeIcons.arrowLeft,
  AppIconName.forward: FontAwesomeIcons.arrowRight,
  AppIconName.up: FontAwesomeIcons.arrowUp,
  AppIconName.down: FontAwesomeIcons.arrowDown,
  AppIconName.close: FontAwesomeIcons.rectangleXmark,
  AppIconName.externalLink: FontAwesomeIcons.arrowUpRightFromSquare,
  AppIconName.money: FontAwesomeIcons.dollarSign,
  AppIconName.coins: FontAwesomeIcons.coins,
  AppIconName.card: FontAwesomeIcons.solidCreditCard,
  AppIconName.invoice: FontAwesomeIcons.fileInvoiceDollar,
  AppIconName.chartUp: FontAwesomeIcons.chartLine,
  AppIconName.chartDown: FontAwesomeIcons.solidChartBar,
  AppIconName.email: FontAwesomeIcons.solidEnvelope,
  AppIconName.phone: FontAwesomeIcons.phone,
  AppIconName.chat: FontAwesomeIcons.solidComment,
  AppIconName.support: FontAwesomeIcons.solidLifeRing,
  AppIconName.help: FontAwesomeIcons.solidCircleQuestion,
  AppIconName.list: FontAwesomeIcons.listUl,
  AppIconName.listOrdered: FontAwesomeIcons.listOl,
  AppIconName.filter: FontAwesomeIcons.filter,
  AppIconName.sort: FontAwesomeIcons.sort,
  AppIconName.sortUp: FontAwesomeIcons.sortUp,
  AppIconName.sortDown: FontAwesomeIcons.sortDown,
  AppIconName.checkList: FontAwesomeIcons.listCheck,
  AppIconName.login: FontAwesomeIcons.rightToBracket,
  AppIconName.logout: FontAwesomeIcons.rightFromBracket,
  AppIconName.lock: FontAwesomeIcons.lock,
  AppIconName.unlock: FontAwesomeIcons.lockOpen,
  AppIconName.key: FontAwesomeIcons.key,
  AppIconName.shield: FontAwesomeIcons.shieldHalved,
  AppIconName.report: FontAwesomeIcons.chartLine,
  AppIconName.reportBar: FontAwesomeIcons.solidChartBar,
  AppIconName.reportPie: FontAwesomeIcons.chartPie,
  AppIconName.print: FontAwesomeIcons.print,
  AppIconName.downloadReport: FontAwesomeIcons.fileArrowDown,
  AppIconName.qrCode: FontAwesomeIcons.qrcode,
  AppIconName.parking: FontAwesomeIcons.squareParking,
  AppIconName.medal: FontAwesomeIcons.medal,
};
