/// Company: CETAM
/// Project: QParking
/// File: app_icons.dart
/// Created on: 13/12/2025
/// Created by: Rodrigo Peña
/// Approved by: Gamaliel Juarez
///
/// Changelog:
/// - ID: 1 | Modified on: 13/12/2025 |
/// Modified by: Rodrigo Peña |
/// Description: Standardized icon catalog with English comments. |
library;

import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:flutter/material.dart';

enum AppIconName {
  user,
  userCircle,
  userAdd,
  userRemove,
  userGroup,
  userTie, // Used in SlideMenu profile
  add,
  edit,
  delete,
  view,
  viewOff,
  save,
  cancel,
  send,
  download,
  upload,
  search,
  refreshArrows,
  success,
  error,
  warning,
  info,
  pending,
  notification,
  notificationOff,
  file,
  filePdf,
  fileWord,
  fileExcel,
  fileImage,
  folder,
  clock,
  folderOpen,
  uploadArrow,
  downloadArrow,
  attachment,
  refreshArrow,
  loading,
  settings,
  process,
  sync,
  home, // Used in SlideMenu
  dashboard,
  menu,
  back,
  forward,
  up,
  down,
  close,
  externalLink,
  money,
  coins,
  card, // Used in SlideMenu
  invoice,
  chartUp,
  chartDown,
  email,
  phone,
  chat,
  support,
  help,
  star,
  list, // Used in SlideMenu
  listOrdered,
  filter,
  sort,
  sortUp,
  sortDown,
  checkList,
  login,
  logout, // Used in SlideMenu
  lock,
  unlock,
  key,
  shield,
  report,
  reportBar,
  reportPie,
  print,
  downloadReport,
  qrCode,
  parking,
  medal,
  iconic,
  calendar,
  bell
}

final Map<AppIconName, IconData> kAppIconMap = {
  AppIconName.user: FontAwesomeIcons.solidUser,
  AppIconName.userCircle: FontAwesomeIcons.solidCircleUser,
  AppIconName.userAdd: FontAwesomeIcons.userPlus,
  AppIconName.userRemove: FontAwesomeIcons.userMinus,
  AppIconName.userGroup: FontAwesomeIcons.users,
  AppIconName.userTie: FontAwesomeIcons.userTie,
  AppIconName.add: FontAwesomeIcons.plus,
  AppIconName.edit: FontAwesomeIcons.solidPenToSquare,
  AppIconName.delete: FontAwesomeIcons.trash,
  AppIconName.view: FontAwesomeIcons.solidEye,
  AppIconName.viewOff: FontAwesomeIcons.solidEyeSlash,
  AppIconName.save: FontAwesomeIcons.solidFloppyDisk,
  AppIconName.cancel: FontAwesomeIcons.xmark,
  AppIconName.send: FontAwesomeIcons.solidPaperPlane,
  AppIconName.download: FontAwesomeIcons.download,
  AppIconName.upload: FontAwesomeIcons.upload,
  AppIconName.search: FontAwesomeIcons.magnifyingGlass,
  AppIconName.refreshArrows: FontAwesomeIcons.arrowsRotate,
  AppIconName.success: FontAwesomeIcons.solidCircleCheck,
  AppIconName.error: FontAwesomeIcons.circleXmark,
  AppIconName.bell: FontAwesomeIcons.bell,
  AppIconName.warning: FontAwesomeIcons.triangleExclamation,
  AppIconName.info: FontAwesomeIcons.circleInfo,
  AppIconName.pending: FontAwesomeIcons.solidClock,
  AppIconName.notification: FontAwesomeIcons.solidBell,
  AppIconName.notificationOff: FontAwesomeIcons.solidBellSlash,
  AppIconName.file: FontAwesomeIcons.solidFile,
  AppIconName.filePdf: FontAwesomeIcons.solidFilePdf,
  AppIconName.fileWord: FontAwesomeIcons.solidFileWord,
  AppIconName.fileExcel: FontAwesomeIcons.solidFileExcel,
  AppIconName.fileImage: FontAwesomeIcons.solidFileImage,
  AppIconName.folder: FontAwesomeIcons.solidFolder,
  AppIconName.folderOpen: FontAwesomeIcons.solidFolderOpen,
  AppIconName.uploadArrow: FontAwesomeIcons.arrowUp,
  AppIconName.downloadArrow: FontAwesomeIcons.arrowDown,
  AppIconName.attachment: FontAwesomeIcons.paperclip,
  AppIconName.refreshArrow: FontAwesomeIcons.arrowRotateRight,
  AppIconName.loading: FontAwesomeIcons.spinner,
  AppIconName.clock: FontAwesomeIcons.clock,
  AppIconName.settings: FontAwesomeIcons.gear,
  AppIconName.process: FontAwesomeIcons.gears,
  AppIconName.sync: FontAwesomeIcons.sync,
  AppIconName.home: FontAwesomeIcons.house,
  AppIconName.dashboard: FontAwesomeIcons.gaugeHigh,
  AppIconName.menu: FontAwesomeIcons.bars,
  AppIconName.back: FontAwesomeIcons.arrowLeft,
  AppIconName.forward: FontAwesomeIcons.arrowRight,
  AppIconName.up: FontAwesomeIcons.arrowUp,
  AppIconName.down: FontAwesomeIcons.arrowDown,
  AppIconName.close: FontAwesomeIcons.rectangleXmark,
  AppIconName.star: FontAwesomeIcons.star,
  AppIconName.externalLink: FontAwesomeIcons.arrowUpRightFromSquare,
  AppIconName.money: FontAwesomeIcons.dollarSign,
  AppIconName.coins: FontAwesomeIcons.coins,
  AppIconName.card: FontAwesomeIcons.solidCreditCard,
  AppIconName.invoice: FontAwesomeIcons.fileInvoiceDollar,
  AppIconName.chartUp: FontAwesomeIcons.chartLine,
  AppIconName.chartDown: FontAwesomeIcons.solidChartBar,
  AppIconName.email: FontAwesomeIcons.solidEnvelope,
  AppIconName.phone: FontAwesomeIcons.phone,
  AppIconName.chat: FontAwesomeIcons.solidComment,
  AppIconName.support: FontAwesomeIcons.solidLifeRing,
  AppIconName.help: FontAwesomeIcons.solidCircleQuestion,
  AppIconName.list: FontAwesomeIcons.listUl,
  AppIconName.listOrdered: FontAwesomeIcons.listOl,
  AppIconName.filter: FontAwesomeIcons.filter,
  AppIconName.sort: FontAwesomeIcons.sort,
  AppIconName.sortUp: FontAwesomeIcons.sortUp,
  AppIconName.sortDown: FontAwesomeIcons.sortDown,
  AppIconName.checkList: FontAwesomeIcons.listCheck,
  AppIconName.login: FontAwesomeIcons.rightToBracket,
  AppIconName.logout: FontAwesomeIcons.rightFromBracket,
  AppIconName.lock: FontAwesomeIcons.lock,
  AppIconName.unlock: FontAwesomeIcons.lockOpen,
  AppIconName.key: FontAwesomeIcons.key,
  AppIconName.shield: FontAwesomeIcons.shieldHalved,
  AppIconName.report: FontAwesomeIcons.chartLine,
  AppIconName.reportBar: FontAwesomeIcons.solidChartBar,
  AppIconName.reportPie: FontAwesomeIcons.chartPie,
  AppIconName.print: FontAwesomeIcons.print,
  AppIconName.downloadReport: FontAwesomeIcons.fileArrowDown,
  AppIconName.qrCode: FontAwesomeIcons.qrcode,
  AppIconName.parking: FontAwesomeIcons.squareParking,
  AppIconName.medal: FontAwesomeIcons.medal,
  AppIconName.calendar: FontAwesomeIcons.solidCalendarDays,
};